### ISSUE TITLE
2000 QT AABB insertion cost 500ms

### ISSUE THREAD

**Issue by yanyouwu** [bartofzo/NativeTrees#2]
I implemented your codes in my project(based on unity oop, not DOTS).
I use a for loop to insert 2000 AABBs to a Quadtree, but it costs 500ms in my project. Is there anything wrong with my usage? 
I can paste my code below if required. 

Your codes runs extremely fast on query operations. 
I tried to buy you a coffee through the website, but I failed. Your codes inspired me i lot, thanks again!
Looking forward to your reply!

**Comment by bartofzo** [comment]
Thanks for the kind words!

It would be helpful to see some code. How are you constructing the tree and how are you inserting the items?

**Comment by yanyouwu** [comment]
- constructing part
![image](https://user-images.githubusercontent.com/5248507/235283608-219aac18-37e4-48d9-b88f-b751cd67b29d.png)
- inserting part
![image](https://user-images.githubusercontent.com/5248507/235283649-1b49d107-b57c-4795-9d35-aae221763e26.png)

- Thanks again for taking the effort to solve my problem!

**Comment by bartofzo** [comment]
Judging from what I can see here it's probably not the Insert call but rather what's going on around it. A couple of things you can try:
- You're creating 2 profiler samplers for every item you're inserting. I can imagine this will cause significant overhead. Have you tried without these? Just try one outside of the loop scope.
- You're calling GetComponent on every dino, which will cause some overhead. I would try caching these.
- Fetch the quadtree from the dictionary outside of the inner loop once. Dictionary access is relatively slow.

Try it with these changes and I think it will solve your problem. If not... what is the radius of the dino's? If they are very large, insertion may be relatively slow.

**Comment by yanyouwu** [comment]
Thanks for your answer!

**Comment by bartofzo** [comment]
No problem. I assume it is fixed so I'm closing this issue
