### ISSUE TITLE
[Question] How to adapt the native octree for 3D navigation,

### ISSUE THREAD

**Issue by Kulgann** [bartofzo/NativeTrees#8]
Hey, I'm trying to adapt the native octree to be used as a 3D pathfinding structure for our game. What I need to do is insert all the AABB's of our scene into it and somehow mark the nodes that still intersect a object at max depth as impassable. Do you have a suggestion on how to proceed ? I'm sorta getting lost in the API. Thank you in advance for your time and effort.

**Comment by bartofzo** [comment]
I don't think this is suitable to use as a structure for pathfinding directly, at least not without a lot of changes. So I can't help you there unfortunately.

I did however build a pathfinding library myself that utilizes this in a navigation mesh, where it is used to accelerate raycast queries to see where an agent is currently:

https://assetstore.unity.com/packages/tools/behavior-ai/anypath-213200

Good luck!
